# 监听端口
port: 10088
# 加密前缀（加密出来的数据内容为 加密前缀-数据内容 ）
before_encode: nia-code
# 加密秘钥（32位，若加密秘钥丢失，则所有数据都无法解密！）
key: eccbc87e4b5ce2fe28308fd9f2a7baf3
# 编码内容（符合当前格式）
encode_value: 富强民主文明和谐自由平等公正法治爱国敬业诚信友善
# 编码混淆内容（符合当前格式）
encode_words: ['啊','嗯','❤','〇','揪~','噗叽','噗','好大❤~~~','~','好硬❤~~~','坏掉了❤~~~','在里面❤~~~','在外面❤','要去了~~~','一起做❤','啊~什么要来了~~~','哈','嗯~']